name: .NET

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    # create dacpac using MSBUILD executable
    - name: create dacpac
      run: |
        & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" "./CustomerClassLibrary/CustomerClassLibrary.Database/CustomerClassLibrary.Database.sqlproj" /p:Configuration=Release
      # Publish an artifact
    - uses: actions/upload-artifact@v2
      with:
        name: DACPAC
        path: ${{ github.workspace }}\CustomerClassLibrary\CustomerClassLibrary.Database\bin\Release\
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
    - name: Codecov upload
      uses: codecov/codecov-action@v2
